'use strict';

// =====================================================
// github-pr.js - GitHub Pull Request 自動作成
//
// 役割:
//   フィーチャーブランチを作成し、Claude Code の成果物を
//   Push した上で GitHub Pull Request を自動作成する。
//
// 重要:
//   PR の自動マージは行いません。
//   必ず人間が確認してからマージしてください。
//
// 必要な .env 設定:
//   ENABLE_PR=true
//   GITHUB_TOKEN=ghp_xxxxxxxxxx    （Personal Access Token、repo権限必須）
//   GITHUB_REPO=username/repo      （例: tanaka/ai-worker-output）
//   GITHUB_BRANCH=main             （PR のマージ先ブランチ）
//   GIT_REPO_PATH=...              （省略時: AI_WORKERルート）
//
// PR作成フロー:
//   1. フィーチャーブランチ作成: ai/task-XXXX
//   2. タスクの成果物を force-add（gitignore 除外対策）
//   3. コミット
//   4. Push
//   5. GitHub API で PR 作成
//   6. Discord 通知（マージは人間が行う）
// =====================================================

const { execSync } = require('child_process');
const fs           = require('fs');
const path         = require('path');
const os           = require('os');
const logger       = require('./logger');

// ─── 設定 ───
const GITHUB_TOKEN  = process.env.GITHUB_TOKEN;
const GITHUB_REPO   = process.env.GITHUB_REPO;
const GITHUB_BRANCH = process.env.GITHUB_BRANCH || 'main';
const GIT_REPO_PATH = process.env.GIT_REPO_PATH || path.join(__dirname, '..', '..');

// ─────────────────────────────────────────────────────
// PR タイトルを生成
// ─────────────────────────────────────────────────────
function generatePRTitle(prompt) {
  const summary = prompt.slice(0, 55).replace(/[\r\n]+/g, ' ');
  const isNew = /作って|追加|create|add|新機能|実装/i.test(prompt);
  const isFix = /修正|直して|エラー|バグ|fix|bug/i.test(prompt);
  const type  = isNew ? 'feat' : isFix ? 'fix' : 'chore';
  return `${type}: [AI] ${summary}`;
}

// ─────────────────────────────────────────────────────
// PR 本文を生成（初心者向けの説明付き）
// ─────────────────────────────────────────────────────
function generatePRBody(prompt, taskId, reviewResult, codexResult) {
  const timestamp  = new Date().toLocaleString('ja-JP');
  const verdict    = reviewResult?.verdict || '未実施';
  const dangerLevel = verdict === '却下推奨' ? '高' : verdict === '修正推奨' ? '中' : '低';
  const dangerEmoji = { '高': '🔴', '中': '🟡', '低': '🟢' }[dangerLevel];
  const verdictEmoji = { '問題なし': '🟢', '修正推奨': '🟡', '却下推奨': '🔴' }[verdict] || '📝';

  // Codex フィードバック適用有無
  const codexLine = codexResult
    ? `| Codex フィードバック | 適用済み（${codexResult.verdict}） |`
    : `| Codex フィードバック | 未適用 |`;

  // 変更理由の推測
  const changeReason = /作って|実装|追加/i.test(prompt)
    ? '新機能の追加'
    : /修正|直して|バグ/i.test(prompt)
    ? 'バグ修正・改善'
    : '機能改善';

  // 危険度に応じた注意書き
  const dangerNote = {
    '高': '⚠️ **重要**: 認証・設定・削除系の変更が含まれています。管理者が確認してください。',
    '中': '💡 **確認推奨**: 設定や依存関係の変更が含まれる可能性があります。',
    '低': '✅ 通常の変更です。内容を確認してマージしてください。',
  }[dangerLevel];

  return [
    `## 【変更内容】`,
    ``,
    `${prompt.slice(0, 500)}`,
    ``,
    `---`,
    ``,
    `## 【変更理由】`,
    ``,
    `${changeReason}のために Claude Code が自動生成しました。`,
    ``,
    `---`,
    ``,
    `## 【AIレビュー結果】`,
    ``,
    `| 項目 | 結果 |`,
    `|------|------|`,
    `| AIレビュー | ${verdictEmoji} ${verdict} |`,
    codexLine,
    `| 危険度 | ${dangerEmoji} ${dangerLevel} |`,
    `| 実行日時 | ${timestamp} |`,
    `| タスクID | \`${taskId}\` |`,
    ``,
    `---`,
    ``,
    `## 【初心者向け説明】`,
    ``,
    `${dangerNote}`,
    ``,
    `**このPRをマージすると何が起きるか:**`,
    `- AI が生成したコードが、リポジトリに追加されます。`,
    `- 変更内容は上記の「変更内容」セクションを参照してください。`,
    ``,
    `**マージ前に確認してほしいこと:**`,
    `- [ ] 変更内容を読んで、意図通りであることを確認する`,
    `- [ ] 危険なコマンドや意図しない削除が含まれていないか確認する`,
    `- [ ] テストや動作確認が必要な場合は実施する`,
    ``,
    `> ⚠️ **このPRは AI が自動生成しました。自動マージは行われません。**`,
    `> 内容を確認してから手動でマージしてください。`,
    ``,
    `---`,
    ``,
    `_Generated by AI_WORKER Phase3 | Task: \`${taskId}\`_`,
  ].join('\n');
}

// ─────────────────────────────────────────────────────
// GitHub REST API で PR を作成
// ─────────────────────────────────────────────────────
async function createGitHubPR({ title, body, head, base }) {
  if (!GITHUB_TOKEN || !GITHUB_REPO) {
    throw new Error('PR作成には GITHUB_TOKEN と GITHUB_REPO が必要です');
  }

  const [owner, repo] = GITHUB_REPO.split('/');
  if (!owner || !repo) {
    throw new Error(`GITHUB_REPO の形式が正しくありません（例: username/repo）: ${GITHUB_REPO}`);
  }

  logger.info(`GitHub PR 作成: ${head} → ${base} | ${owner}/${repo}`);

  const response = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/pulls`,
    {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${GITHUB_TOKEN}`,
        'Accept':        'application/vnd.github+json',
        'Content-Type':  'application/json',
        'X-GitHub-Api-Version': '2022-11-28',
      },
      body: JSON.stringify({ title, body, head, base }),
    }
  );

  if (!response.ok) {
    let errMsg = `HTTP ${response.status}`;
    try {
      const errData = await response.json();
      errMsg = errData.message || errMsg;
      // ブランチが存在しないエラーの詳細
      if (errData.errors) {
        errMsg += ' | ' + errData.errors.map(e => e.message).join(', ');
      }
    } catch { /* ignore */ }
    throw new Error(`GitHub PR 作成失敗: ${errMsg}`);
  }

  return await response.json();
}

// ─────────────────────────────────────────────────────
// git をフィーチャーブランチに切り替えてコミット
// ─────────────────────────────────────────────────────
function switchToFeatureBranch(repoPath, featureBranch, baseBranch) {
  // ベースブランチに移動（失敗しても続行）
  try {
    execSync(`git checkout ${baseBranch}`, { cwd: repoPath, stdio: 'pipe' });
  } catch {
    logger.debug(`git checkout ${baseBranch} 失敗（現在のブランチで続行）`);
  }

  // フィーチャーブランチを作成（すでに存在する場合はスイッチ）
  try {
    execSync(`git checkout -b ${featureBranch}`, { cwd: repoPath, stdio: 'pipe' });
  } catch {
    // すでに存在する場合
    execSync(`git checkout ${featureBranch}`, { cwd: repoPath, stdio: 'pipe' });
    logger.debug(`既存のフィーチャーブランチに移動: ${featureBranch}`);
  }
}

// ─────────────────────────────────────────────────────
// ベースブランチに戻す（安全に）
// ─────────────────────────────────────────────────────
function returnToBaseBranch(repoPath, baseBranch) {
  try {
    execSync(`git checkout ${baseBranch}`, { cwd: repoPath, stdio: 'pipe' });
    logger.debug(`ベースブランチに戻りました: ${baseBranch}`);
  } catch (e) {
    logger.warn(`ベースブランチへの復帰失敗: ${e.message}`);
  }
}

// ─────────────────────────────────────────────────────
// メイン: フィーチャーブランチ作成 → コミット → Push → PR作成
//
// 戻り値:
//   { skipped: true, reason }          変更なしの場合
//   { skipped: false, prUrl, prNumber,
//     prTitle, featureBranch }         PR作成成功
// ─────────────────────────────────────────────────────
async function createPRWorkflow(prompt, taskId, reviewResult, codexResult) {
  const repoPath      = GIT_REPO_PATH;
  const featureBranch = `ai/${taskId}`;
  const baseBranch    = GITHUB_BRANCH;

  logger.info(`PR ワークフロー開始 | タスク: ${taskId} | ブランチ: ${featureBranch}`);

  // フィーチャーブランチへ切り替え
  switchToFeatureBranch(repoPath, featureBranch, baseBranch);

  // タスクの成果物を force-add（workspace/ が gitignore されていても強制追加）
  const taskPath = `workspace/${taskId}`;
  try {
    execSync(`git add -f "${taskPath}/"`, { cwd: repoPath, stdio: 'pipe' });
    logger.info(`git add -f: ${taskPath}/`);
  } catch (addErr) {
    // force-add が失敗したら通常の add を試みる
    logger.warn(`git add -f 失敗: ${addErr.message}。git add . を試みます。`);
    execSync('git add .', { cwd: repoPath, stdio: 'pipe' });
  }

  // ステージング確認（何もなければスキップ）
  const staged = execSync('git diff --cached --name-only', {
    cwd: repoPath, stdio: 'pipe', encoding: 'utf8'
  }).trim();

  if (!staged) {
    returnToBaseBranch(repoPath, baseBranch);
    return {
      skipped: true,
      reason: 'ステージングするファイルがありませんでした（変更なし）',
    };
  }

  // コミット（日本語安全のため一時ファイル経由）
  const prTitle   = generatePRTitle(prompt);
  const commitBody = `AI_WORKER 自動PR\nタスクID: ${taskId}\n日時: ${new Date().toLocaleString('ja-JP')}\n\n依頼内容:\n${prompt.slice(0, 200)}`;
  const tmpFile    = path.join(os.tmpdir(), `ai_pr_${taskId}.txt`);

  try {
    fs.writeFileSync(tmpFile, `${prTitle}\n\n${commitBody}`, 'utf8');
    execSync(`git commit -F "${tmpFile}"`, {
      cwd: repoPath,
      stdio: 'pipe',
      env: { ...process.env, LANG: 'UTF-8' },
    });
    logger.info(`git commit 完了: ${prTitle}`);
  } finally {
    try { fs.unlinkSync(tmpFile); } catch { /* ignore */ }
  }

  // リモートを設定してフィーチャーブランチを Push
  if (GITHUB_TOKEN && GITHUB_REPO) {
    const remoteUrl = `https://${GITHUB_TOKEN}@github.com/${GITHUB_REPO}.git`;
    try {
      execSync(`git remote set-url origin "${remoteUrl}"`, { cwd: repoPath, stdio: 'pipe' });
    } catch {
      execSync(`git remote add origin "${remoteUrl}"`, { cwd: repoPath, stdio: 'pipe' });
    }

    logger.info(`git push: ${featureBranch}`);
    execSync(`git push origin ${featureBranch} --set-upstream`, {
      cwd: repoPath,
      stdio: 'pipe',
      timeout: 30000,
      env: { ...process.env, GIT_TERMINAL_PROMPT: '0' },
    });
    logger.info('git push 完了');
  } else {
    logger.warn('GITHUB_TOKEN/GITHUB_REPO 未設定。Push をスキップします。');
    returnToBaseBranch(repoPath, baseBranch);
    return { skipped: true, reason: 'GITHUB_TOKEN または GITHUB_REPO が未設定です' };
  }

  // ベースブランチに戻す
  returnToBaseBranch(repoPath, baseBranch);

  // GitHub API で PR 作成
  const prBody = generatePRBody(prompt, taskId, reviewResult, codexResult);
  const prData = await createGitHubPR({
    title: prTitle,
    body:  prBody,
    head:  featureBranch,
    base:  baseBranch,
  });

  logger.info(`PR 作成完了: #${prData.number} ${prData.html_url}`);

  return {
    skipped:       false,
    prUrl:         prData.html_url,
    prNumber:      prData.number,
    prTitle:       prData.title,
    featureBranch,
    baseBranch,
    stagedFiles:   staged.split('\n').filter(Boolean),
  };
}

module.exports = { createPRWorkflow, createGitHubPR, generatePRTitle, generatePRBody };
